/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_security_jni_JNIInvocation */

#ifndef _Included_com_security_jni_JNIInvocation
#define _Included_com_security_jni_JNIInvocation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_security_jni_JNIInvocation
 * Method:    getScore
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_security_jni_JNIInvocation_getScore
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_security_jni_JNIInvocation
 * Method:    getPatternScore
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_security_jni_JNIInvocation_getPatternScore
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
